### ISSUE TITLE
Test dev/2.0.0 with the latest WordPress

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#104]
@esudalaimadan 

Take the latest code from dev/2.0.0 and see if all the modules are working properly.

**Comment by sudar** [comment]
Hello @mariadanieldeepak 

Can you take the latest code from `dev/2.0.0` and do a round of testing?

**Comment by mariadanieldeepak** [comment]
@sudar,

I've fully tested the dev/2.0.0 branch and identified the following issues. Kindly let me know if you need anything further.

- [ ] https://github.com/sudar/bulk-move/issues/106 Fix npm vulnerabilities
- [ ] https://github.com/sudar/bulk-move/issues/107 Screen options show/hide not working
- [ ] https://github.com/sudar/bulk-move/issues/108 Wording doesn't look correct
- [x] https://github.com/sudar/bulk-move/issues/109 JS Error: select2 is not a function
- [ ] https://github.com/sudar/bulk-move/issues/110 Move Posts By Custom Taxonomy :: Incorrect Confirmation message
- [ ] https://github.com/sudar/bulk-move/issues/112 Move Posts By Category :: No confirmation modal
- [ ] https://github.com/sudar/bulk-move/issues/113 No Confirmational modal

**Comment by sudar** [comment]
@esudalaimadan 

Test the `dev/2.0.0` branch with WordPress 5.4 and see if there are glaring issues.

**Comment by esudalaimadan** [comment]
@sudar functionality wise all modules are working.  Styling also looks good.

Issues found:
a) Confirmation dialog does not appear for all the modules in Move posts by category, Move posts by tag, Move posts from tag to category and Move posts from category to tag.
b) Wrong confirmation dialog appears for Move Posts by custom taxonomy.
